global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'mysqld-exporter'
    static_configs:
      - targets: ['mysqld-exporter:9104']
  - job_name: 'fpm-exporter'
    static_configs:
      - targets: ['fpm-exporter:9253']