global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'mysqld-exporter'
    static_configs:
      - targets: ['mysqld-exporter:9104']
  - job_name: 'fpm-exporter'
    metrics_path: /status
    params:
      openmetrics: [""]
    static_configs:
      - targets: ['app:80']