{
 "title": "PHP FPM",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Up",
   "type": "stat",
   "description": "Could pool www using a static PM on PHP-FPM be reached?",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "phpfpm_up", "legendFormat": "PHP FPM Up" }
   ]
  },
  {
   "title": "Running For",
   "type": "stat",
   "description": "The time since FPM has started.",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "phpfpm_start_since", "legendFormat": "Peak Memory (since start)" }
   ]
  },
  {
   "title": "Peak Memory",
   "type": "stat",
   "description": "The memory usage peak since FPM has started.",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "phpfpm_memory_peak", "legendFormat": "Peak Memory (since start)" }
   ]
  },
  {
   "title": "Max Active Processes",
   "type": "stat",
   "description": "The maximum number of active processes since FPM has started.",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "phpfpm_max_active_processes", "legendFormat": "Peak Memory (since start)" }
   ]
  },
  {
   "title": "Accepted Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "increase(phpfpm_accepted_connections[1m])",
     "legendFormat": "Accepted Connections"
    }
   ]
  },
  {
   "title": "Processes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "targets": [
    { "expr": "phpfpm_total_processes", "legendFormat": "Total Processes" },
    { "expr": "phpfpm_active_processes", "legendFormat": "Active Processes" }
   ]
  }
 ]
}